### ISSUE TITLE
Could not determine release URL

### ISSUE THREAD

**Issue by dkarter** [lwiechec/asdf-eza#4]
**Describe the bug**

Cannot install eza via asdf after adding this plugin

**Steps to reproduce**

1. Install plugin (asdf plugin-add eza)
2. Attempt to install eza via asdf (asdf install eza latest)

**Expected behavior**

Eza is installed and binary is available

**Screenshots**

![CleanShot 2023-12-11 at 22 25 18@2x](https://github.com/lwiechec/asdf-eza/assets/551858/6b857c3a-38c4-4d45-ba0c-dad3b6d29190)

**Additional context**

N/A

**Comment by lwiechec** [comment]
thanks for reporting @dkarter 

Hmm, I am having trouble reproducing, but I am installing Linux version of `eza`:

![2023-12-12_10-36](https://github.com/lwiechec/asdf-eza/assets/376537/7c86f858-1c1e-4165-af14-b2be98ea98bc)

I wonder which OS are you running - is it OS X?

**Comment by dkarter** [comment]
Sorry, should have mentioned I'm on macOS Sonoma (latest) running on Apple Silicon

**Comment by lwiechec** [comment]
no problem! so, the problem you are experiencing is due to the fact that eza does not publish the binaries for mac (there is even [an open ticket about it](https://github.com/eza-community/eza/issues/228)). `asdf-eza` is just checking the releases page and cannot find a distribution for mac OS...

**Comment by dkarter** [comment]
Makes sense! I'll follow up there. I do wonder why they chose not to use GH workflow which makes this relatively simple. 

Thanks for looking into it and for building this plugin! Cheers!

**Comment by sirenkovladd** [comment]
As a workaround, [asdf-eza now](https://github.com/lwiechec/asdf-eza/pull/5) gets the binary from the https://github.com/cargo-bins/cargo-quickinstall repository, and you can use this plugin for macos on arm architecture
